spring.application.name=batchApplication

spring.profiles.include=dev

# HikariCP ??
#spring.datasource.hikari.maximum-pool-size=10
#spring.datasource.hikari.minimum-idle=5
#spring.datasource.hikari.idle-timeout=30000
#spring.datasource.hikari.max-lifetime=1800000
#spring.datasource.hikari.connection-timeout=30000

# Spring Batch ??
spring.batch.jdbc.initialize-schema=always
# ?? ?? ??
#spring.batch.job.enabled=false
# ?????? ?? ? ??? Job ??
spring.batch.job.name=helloJob

# health check settings
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always