spring.application.name=batchApplication

spring.profiles.include=local

# HikariCP ??
#spring.datasource.hikari.maximum-pool-size=10
#spring.datasource.hikari.minimum-idle=5
#spring.datasource.hikari.idle-timeout=30000
#spring.datasource.hikari.max-lifetime=1800000
#spring.datasource.hikari.connection-timeout=30000

spring.jpa.hibernate.ddl-auto=validate

# Spring Batch ??
spring.batch.jdbc.initialize-schema=embedded
# ?? ?? ??
#spring.batch.job.enabled=false
# ?????? ?? ? ??? Job ??
spring.batch.job.name=helloJob

# health check settings
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

# Concurrent Hash Map caching
spring.cache.cache-names=board
# for check cache provider, using this.
logging.level.org.springframework.cache=DEBUG
logging.level.org.springframework.boot.autoconfigure.cache=DEBUG