spring.application.name=batchApplication

spring.profiles.include=local

# HikariCP ??
#spring.datasource.hikari.maximum-pool-size=10
#spring.datasource.hikari.minimum-idle=5
#spring.datasource.hikari.idle-timeout=30000
#spring.datasource.hikari.max-lifetime=1800000
#spring.datasource.hikari.connection-timeout=30000

spring.jpa.hibernate.ddl-auto=validate

# Spring Batch ??
spring.batch.jdbc.initialize-schema=embedded
# ?? ?? ??
#spring.batch.job.enabled=false
# ?????? ?? ? ??? Job ??
spring.batch.job.name=helloJob

# health check settings
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

# Concurrent Hash Map caching
spring.cache.cache-names=board
spring.cache.redis.time-to-live=10m
spring.data.redis.cluster.nodes=\
  redis-node-1:6479,\
  redis-node-2:6480,\
  redis-node-3:6481,\
  redis-node-4:6482,\
  redis-node-5:6483,\
  redis-node-6:6484
spring.data.redis.cluster.max-redirects=3
spring.data.redis.timeout=5000
spring.data.redis.password=password

# for check cache provider, using this.
logging.level.org.springframework.cache=DEBUG
logging.level.org.springframework.boot.autoconfigure.cache=DEBUG